# Enter the wording in urdu and convert it into english language.
words = {
    #one condition first letter are capital and remain used short alphabet
    "Pani": "Water",
    "Kitab": "Book",
    "Ghar": "House",
    "Dost": "Friend",
    "Khana": "Food",
    "Larka": "Boy",
    "Larki": "Girl",
    "Walid": "Father",
    "Walida": "Mother",
    "Bhai": "Brother",
    "Behan": "Sister",
    "Ustad": "Teacher",
    "Talib": "Student",
    "School": "School",
    "College": "College",
    "Darakht": "Tree",
    "Phool": "Flower",
    "Parinda": "Bird",
    "Janwar": "Animal",
    "Kutta": "Dog",
    "Billi": "Cat",
    "Seb": "Apple",
    "Aam": "Mango",
    "Kela": "Banana",
    "Angoor": "Grapes",
    "Doodh": "Milk",
    "Chai": "Tea",
    "Roti": "Bread",
    "Chawal": "Rice",
    "Namak": "Salt",
    "Cheeni": "Sugar",
    "Qalam": "Pen",
    "Kursi": "Chair",
    "Mez": "Table",
    "Darwaza": "Door",
    "Khirki": "Window",
    "Suraj": "Sun",
    "Chand": "Moon",
    "Sitara": "Star",
    "Zameen": "Earth",
    "Asman": "Sky",
    "Nadi": "River",
    "Samandar": "Sea",
    "Pahar": "Mountain",
    "Shehar": "City",
    "Gaon": "Village",
    "Bazar": "Market",
    "Kapra": "Cloth",
    "Joota": "Shoes",
    "Topi": "Cap"
}
print("ENTER THE FIRST LETTER OF URDU ARE CAPITAL REMAIN SHORT USED:")
word=input("Enterr the meanning of the text:")
print("your word English means:",words[word])
