# we can take user value and print in set form.
s=set()
n=input("Enter your number:")
s.add(int(n))
n=input("Enter your number:")
s.add(int(n))
n=input("Enter your number:")
s.add(int(n))
n=input("Enter your number:")
s.add(int(n))
n=input("Enter your number:")
s.add(int(n))
n=input("Enter your number:")
s.add(int(n))
n=input("Enter your number:")
s.add(int(n))
print(s)
